### ISSUE TITLE
Testing Setup

### ISSUE THREAD

**Issue by kater1** [ustwo/ustwo.com-frontend#23]
### TASKS
- [ ] Set up Travis CI
- [ ] Set up unit testing framework
- [ ] Write tests for existing code; SVG animation class
