### ISSUE TITLE
^Track if homepage is read

### ISSUE THREAD

**Issue by jgunson** [ustwo/ustwo.com-frontend#36]
### Description

After discussion with the dev team (@daaain & @collingo), implementing all the custom events that need to be tracked will take a considerable amount of effort - each event would need to be implemented manually, as opposed to combining the events that GA tracks as standard with custom events in order to create our required goals (and then track the  conversion rates of those goals).
### Investigation
- Can we create a report that combines standard GA events (Time on Page) with a custom event (Scroll Position on Homepage) that gives enough data to determine whether or not the content has been read?
### Task List
- [x] Set-up staging.ustwo.com as property in GA
- [x] Create tracking code and insert into staging head script
- [x] Add tracking ID to Homepage
- [x] Implement scroll tracking for visitor homepage
- [x] Check that scroll tracking goes through to GA
- [x] Ask a number of ustwobies to go onto the [staging.ustwo.com](staging.ustwo.com) homepage
- [x] Using collected data set-up report that combines `Time on Page + Scroll position` to assess Conversion Rate
