### ISSUE TITLE
^Test HeapAnalytics

### ISSUE THREAD

**Issue by jgunson** [ustwo/ustwo.com-frontend#40]
### Description

While we can set-up / combine / create custom events in GA (see [Issue 36](https://github.com/ustwo/ustwo.com-frontend/issues/36) it requires quite a bit of development effort and additional configuration in GA). Furthermore with the current GA subscription (free) we can only create a maximum of 20 goals for any given property.
### Investigation
- Can an alternative analytics solution (i.e. [HeapAnalytics](https://heapanalytics.com/) give us the information we need, with less effort than GA?
### Task List
- [x] Create HeapAnalytics account
- [x] Install tracking code on Staging site (staging.ustwo.com)
- [x] Send scroll tracking to Heap via custom event (API info [here](https://heapanalytics.com/docs/custom-api)
- [x] Set up tracking events and Content is Read funnel
