### ISSUE TITLE
Join us

### ISSUE THREAD

**Issue by jgunson** [ustwo/ustwo.com-frontend#58]
### Intent

The join us page is a significant touch point within the site, and has yet to be explored. @baramus to add additional detail.
### Outcome

Design multiple, different approaches that can be reviewed with the team, before deciding on a solution for implementation
### Tasks List
- [x] Write / review stories and acceptance criteria
- [x] Develop initial ideas and review with team
- [ ] Finalise designs ready for intial implementation
